---
- name: Update apt-get repo and cache
  apt: update_cache=yes

- name: Install coturn
  apt:
    name: coturn
    state: present

- name: get turn internal ip
  shell: ip route get 1 | sed -n 's/^.*src \([0-9.]*\) .*$/\1/p'
  register: turn_internal

- name: get turn external ip
  shell: curl -s http://whatismyip.akamai.com/
  register: turn_external

- name: Generate turn config
  template:
    src: turnserver.conf.j2
    dest: /etc/turnserver.conf

- name: Configure Log Rotation
  copy:
    src: files/coturn
    dest: /etc/logrotate.d/coturn
    mode: +rw

- name: Creates directory
  ignore_errors: yes
  file:
    path: /etc/turnserver
    state: directory

- name: Creates directory
  ignore_errors: yes
  file:
    path: /etc/systemd/system/coturn.service.d
    state: directory

- name: Configure Log Rotation
  copy:
    src: files/override.conf
    dest: /etc/systemd/system/coturn.service.d/override.conf

- name: run script
  become: True
  shell:
    cmd: "openssl dhparam -dsaparam  -out /etc/turnserver/dhp.pem 2048"

- name: Daemon reload
  become: True
  shell:
    cmd: "systemctl daemon-reload"

- name: Start coturn
  become: True
  shell:
    cmd: "systemctl restart coturn"