---
- name: get nfs server ip
  shell: ip route get 1 | sed -n 's/^.*src \([0-9.]*\) .*$/\1/p'
  register: nfs_server

- name: get host subnet
  shell: ip -o -f inet addr show $(ip r | grep default | awk '/default/ {print $5}') | awk '/scope global/ {print $4}' | perl -ne 's/(?<=\d.)\d{1,3}(?=\/)/0/g; print;'
  register: host_subnet

- name: debug nfs internal ip
  debug:
    msg: "{{ nfs_server }}"

- name: debug host subnet
  debug:
    msg: "{{ host_subnet }}"